### ISSUE TITLE
fix: supress stack trace when indexd document already exists

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#65]
As an ACED user, when I re-upload files, the helpful error message is obscured by the stacktrace.

Helpful:
>[ERROR] gen3_util.files.manifest indexd record already exists, consider using --overwrite. 0f371f8f-a26c-5d56-a166-ab832f720f50 409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists for url: https://aced-idp.org/index/index/

```[2024-02-28 09:51:46,680] [ERROR] gen3_util.files.manifest indexd record already exists, consider using --overwrite. 0f371f8f-a26c-5d56-a166-ab832f720f50 409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists for url: https://aced-idp.org/index/index/
  0%|                                                                                           | 0/3 [00:00<?, ?it/s]
[2024-02-28 09:51:46,680] [ERROR] gen3_util.repo 409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists for url: https://aced-idp.org/index/index/
Traceback (most recent call last):
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/repo/cli.py", line 247, in push_cli
    raise e
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/repo/cli.py", line 236, in push_cli
    push(config, restricted_project_id=restricted_project_id, overwrite_index=overwrite_index,
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/repo/pusher.py", line 35, in push
    manifest_entries = upload_commit_to_indexd(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/files/manifest.py", line 209, in upload_commit_to_indexd
    _ = _write_indexd(
        ^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/files/manifest.py", line 160, in _write_indexd
    raise e
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3_util/files/manifest.py", line 147, in _write_indexd
    response = index_client.create_record(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/gen3/index.py", line 420, in create_record
    rec = self.client.create(
          ^^^^^^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/indexclient/client.py", line 286, in create
    resp = self._post(
           ^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/indexclient/client.py", line 41, in timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/indexclient/client.py", line 412, in _post
    handle_error(resp)
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/indexclient/client.py", line 35, in handle_error
    resp.raise_for_status()
  File "/home/users/leejor/.conda/envs/py3-11.third/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists for url: https://aced-idp.org/index/index/
msg: '409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists
  for url: https://aced-idp.org/index/index/'
exception: '409 Client Error: did "0f371f8f-a26c-5d56-a166-ab832f720f50" already exists
  for url: https://aced-idp.org/index/index/'```

**Comment by matthewpeterkort** [comment]
> As an ACED user, when I re-upload files, the helpful error message is obscured by the stacktrace.

This is going to be solved in https://github.com/ACED-IDP/gen3_util/tree/feature/reset-upgrades branch

**Comment by bwalsh** [comment]
addressed here https://github.com/ACED-IDP/gen3_util/blob/514030ab5d1e41743df0076f9aa81ea79ef1eabb/gen3_tracker/git/cli.py#L218-L220
